### ISSUE TITLE
Feat: In-App Messaging

### ISSUE THREAD

**Issue by supposedlysam-bb** [Collectx-exchange/iterable_flutter#1]
Thanks for starting up this repo! 

My company is currently looking to integrate our Flutter app with Iterable for in-app messaging.

#### 1) Triggered In-App Message (not just on startup)
We would like to be able to show an in-app message to our users once they've gotten past the splash screen (resources have loaded) or when they get done with onboarding. 

#### 2) Only Show Once
We would like for the same in-app message to only be shown to the user once.

#### 3) Daily Message Limits
We would like to limit how many in-app messages users see in a day (preferably 1) so we don't overload them and create a queue.

#### We should be able to deep link by tapping on a message

Please let me know if this is already on your roadmap. Otherwise, I would greatly appreciate this feature being added in the future!

**Comment by Gabriel-Azevedo** [comment]
Hi @supposedlysam-bb 

This repo was created for internal use only, hence the subpar coding and some workarounds. 

We did talk to Iterable and decided to make it public so they could help us with some problems, but I don't recommend using it on your own app.

We don't plan on porting all the existing features, and we will only update the repo if we need new features.

Feel free to clone it or open a PR here and I can take a look.

For your questions:

1. It seems to be a limitation with Iterable itself. I couldn't get it to automatically trigger even when using the native SDK. But you can build a custom queue and show the message when needed.

2. I think you can see this in the workflow settings.

3. I think this also can be done on the Iterable dashboard

4. I had to use a third-party package for that (uni_links) but still feels like a workaround.
